[package]
edition = "2018"
name = "crev-wot"
version = "0.22.0"
description = "Scalable, social, Code REView system that we desperately need - Web of Trust library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/cargo-crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["web-of-trust", "dependency", "peer", "review", "identity"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
crev-common = { path = "../crev-common", version = "0.21.1" }
crev-data = { path = "../crev-data", version = "0.22" }
blake2 = "0.9.1"
chrono = { version = "0.4.19", default-features = false }
default = "0.1.2"
log = "0.4.14"
serde = "1.0.126"
serde_yaml = "0.8.17"
thiserror = "1.0.26"
