[package]
edition = "2018"
name = "crev-wot"
version = "0.1.0"
description = "Scalable, social, Code REView system that we desperately need - Web of Trust library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crev-common = { path = "../crev-common", version = "0.17.0" }
miscreant = { version = "0.4", features = ["soft-aes"] }
crev-data = { path = "../crev-data", version = "0.17.0" }
blake2 = "0.8.1"
chrono = "0.4.11"
common_failures = "0.1.1"
crev-recursive-digest = "0.4.0"
default = "0.1.2"
directories = "2.0.2"
failure = "0.1.7"
fnv = "1.0.6"
git2 = "0.11"
ifmt = "0.3.0"
insideout = "0.2.0"
log = "0.4.8"
num_cpus = "1.12.0"
resiter = "0.4.0"
rust-argon2 = "0.8.2"
semver = "0.9.0"
serde = "1.0.106"
serde_cbor = "0.11.1"
serde_yaml = "0.8.11"
tempdir = "0.3.7"
walkdir = "2.3.1"
