[package]
edition = '2018'
name = "cargo-crev"
version = "0.20.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>", "Kornel Lesiński <kornel@geekhood.net>"]
categories = ["development-tools::cargo-plugins"]
default-run = "cargo-crev"
description = "Distibuted Code REView system for verifying security and quality of Cargo dependencies"
documentation = "https://docs.rs/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed", "security"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crev-dev/cargo-crev"

[[bin]]
name = "cargo-crev"
path = "src/main.rs"

[lib]
name = "cargo_crev"
path = "src/lib.rs"

[dependencies]
crev-common = { path = "../crev-common", version = "0.20" }
crev-data = { path = "../crev-data", version = "0.20" }
crev-wot = { path = "../crev-wot", version = "0.20" }
crev-lib = { path = "../crev-lib", version = "0.20" }
anyhow = "1.0.38"
atty = "0.2.14"
cargo = "0.53.0"
cargo-platform = "0.1.1"
crates_io_api = "0.7"
crossbeam = "0.7.3"
crossterm = "0.9.6"
chrono = "0.4.19"
env_logger = { version = "0.8.3", default-features = false, features = ["termcolor", "atty", "humantime"] }
fnv = "1.0.7"
geiger = "0.4.5"
lazy_static = "1.4.0"
num_cpus = "1.13.0"
petgraph = "0.5.1"
rayon = "1.5.0"
resiter = "0.4.0"
rpassword = "5"
serde = "1.0.123"
term = "0.6.1"
termimad = "0.6"
serde_json = "1.0.62"
serde_yaml = "0.8.17"
structopt = "0.3.21"
time = "0.2.25"
tokei = "12.1.2"
walkdir = "2.3.1"
openssl-sys = { version = "0.9.60" }
git2 = "0.13.17"
tempfile = "3.2.0"
rprompt = "1.0.5"
thiserror = "1.0.24"
log = "0.4.14"

[features]
default = ["openssl-sys/vendored"]

documentation = []

[package.metadata.docs.rs]
all-features = true
