# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: fmt
    name: cargo fmt
    description: Format files with cargo fmt.
    entry: cargo fmt --
    language: system
    types: [rust]
    stages: [commit]
    args: []

  - id: test
    name: cargo test
    description: Run tests with cargo test.
    entry: cargo test --
    language: rust
    types: [rust]
    stages: [push]
    args: []
