[package]
edition = "2018"
name = "crev-lib"
version = "0.19.0"
description = "Scalable, social, Code REView system that we desperately need - core library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
crev-common = { path = "../crev-common", version = "0.19" }
miscreant = { version = "0.4", features = ["soft-aes"] }
crev-data = { path = "../crev-data", version = "0.19" }
crev-wot = { path = "../crev-wot", version = "0.19" }
blake2 = "0.8.1"
chrono = "0.4.19"
crev-recursive-digest = "0.4.0"
default = "0.1.2"
directories = { version = "2", package = "directories-next" }
fnv = "1.0.7"
git2 = "0.13.17"
log = "0.4.14"
num_cpus = "1.13.0"
resiter = "0.4.0"
rust-argon2 = "0.8.3"
serde = "1.0.123"
serde_cbor = "0.11.1"
serde_yaml = "0.8.17"
walkdir = "2.3.1"
thiserror = "1.0.24"
rayon = "1.5.0"
