[package]
edition = '2018'
name = "crev-data"
version = "0.3.0"
description = "Scalable, social, Code REView system that we desperately need - data types library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/dpc/crev"
homepage = "https://github.com/dpc/crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
crev-common = { path = "../crev-common", version = "0.3" }
blake2 = "0.8"
chrono = "0.4"
common_failures = "0.1"
ed25519-dalek = "1.0.0-pre.0"
failure = "0.1"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
hex = "0.3"
rand = "0.5.5"
derive_builder = "0.7"

[dependencies.argonautica]
features = ["serde"]
version = "0.1"
