[package]
edition = '2018'
name = "crev-data"
version = "0.21.0"
description = "Scalable, social, Code REView system that we desperately need - data types library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev-lib"
homepage = "https://github.com/crev-dev/crev"
keywords = ["code", "peer", "review", "verification", "dependencies"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crev-dev/cargo-crev"

[dependencies]
crev-common = { path = "../crev-common", version = "0.21" }
chrono = "0.4.19"
derive_builder = "0.10.2"
ed25519-dalek = "1.0.0"
rand_v07 = { version = "0.7.3", package = "rand" } # for dalek
rand = "0.8.3"
semver = { version = "0.10.0", features = [ "serde" ] }
serde = { version = "1.0.123", features = ["derive"] }
serde_yaml = "0.8.17"
typed-builder = "0.9.0"
thiserror = "1.0.24"
