[package]
edition = "2018"
name = "crev-common"
version = "0.19.0"
description = "Scalable, social, Code REView system that we desperately need - common code"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
base64 = "0.13"
blake2 = "0.8.1"
chrono = "0.4.11"
digest = "0.8.1"
hex = "0.4.2"
rand = "0.7.3"
rprompt = "1.0.5"
serde = "1.0.123"
serde_yaml = "0.8.11"
shell-escape = "0.1.4"
thiserror = "1.0.17"
